version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql-eshop
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_USERNAME=boss
      - MYSQL_ROOT_PASSWORD=WolFHacK702
      - MYSQL_DATABASE=eshop
    ports:
      - 3306:3306
  mongodb:
    image: mongo
    container_name: mongo-eshop
    ports:
      - 27018:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express-eshop
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongo-eshop
volumes:
  data: {}
networks:
  default:
    name: mongo-eshop_network